---
# tasks file for jenkins

- name: Check ubuntu version is supported
  fail:
    msg: 'Ubuntu {{ ansible_lsb.codename }} not supported'
  when: ansible_lsb.codename not in jenkins_supported
  tags:
    - jenkins

- name: Install required packages
  apt:
    name: '{{ item }}'
    state: 'installed'
  with_items:
    - apt-transport-https
    - ca-certificates
  tags:
    - jenkins

- name: Add jenkins apt key
  apt_key:
    url: 'https://pkg.jenkins.io/debian/jenkins.io.key'
    state: 'present'
  tags:
    - jenkins

- name: Add jenkins repo
  apt_repository:
    repo: 'deb https://pkg.jenkins.io/debian binary/'
    state: 'present'
    update_cache: 'yes'
  tags:
    - jenkins

- name: Prevent jenkins to start on install
  copy:
    content: |-
      #!/bin/sh
      exit 101
    dest: '/usr/sbin/policy-rc.d'
    owner: 'root'
    group: 'root'
    mode: '0755'
  changed_when: False
  tags:
    - jenkins

- name: Install jenkins
  apt:
    name: 'jenkins'
    state: 'present'
  tags:
    - jenkins

- name: Remove policy-rc.d
  file:
    name: '/usr/sbin/policy-rc.d'
    state: 'absent'
  changed_when: False
  tags:
    - jenkins

- name: Ensure some dirs exist and belong to {{ jenkins_user }}
  file:
    dest: '{{ item }}'
    state: 'directory'
    owner: '{{ jenkins_user }}'
    group: '{{ jenkins_group }}'
    mode: '0775'
  with_items:
    - '{{ jenkins_log_dir }}'
    - '{{ jenkins_cache_dir }}'
  tags:
    - jenkins

- name: Configure jenkins
  template:
    src: 'default.j2'
    dest: '{{ jenkins_conf_file }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: restart jenkins
  tags:
    - jenkins

- include: '{{ jenkins_init_system }}.yml'
  tags:
    - jenkins
