---
# handlers file for jenkins

- name: restart jenkins
  shell: >
    /bin/true
  notify: 'restart jenkins {{ jenkins_init_system }}'

- name: restart jenkins systemd
  service:
    name: 'jenkins'
    state: 'restarted'

- name: reload jenkins
  shell: >
    /bin/true
  notify: 'reload jenkins {{ jenkins_init_system }}'

- name: reload jenkins systemd
  service:
    name: 'jenkins'
    state: 'reloaded'
